DROP TABLE IF EXISTS duck CASCADE;
CREATE TABLE `duck` (
	`id` bigint generated by default as identity, 
	`age` integer check (age<=20 AND age>=2), 
	`gender` varchar(255), habitat varchar(255), 
	`name` varchar(255) not null, primary key (id)
);
